# Generated by Django 4.2 on 2023-05-07 00:28

from django.db import migrations, models
from django.utils import timezone


def set_sleep_nap_values(apps, schema_editor):
    # The historical model, not core.models.Sleep: the live model carries
    # fields added by later migrations, and selecting them here fails on a
    # fresh database. Only `nap` changes, so the live model's `save` is not
    # needed; the nap window settings still come from the live model.
    from core.models import Sleep as LiveSleep

    Sleep = apps.get_model("core", "Sleep")
    for sleep in Sleep.objects.all():
        sleep.nap = (
            LiveSleep.settings.nap_start_min
            <= timezone.localtime(sleep.start).time()
            <= LiveSleep.settings.nap_start_max
        )
        sleep.save(update_fields=["nap"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_timer_options_remove_timer_duration_and_more"),
        ("dbsettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sleep",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [("can_edit_sleep_settings", "Can edit Sleep settings")],
                "verbose_name": "Sleep",
                "verbose_name_plural": "Sleep",
            },
        ),
        migrations.RemoveField(
            model_name="sleep",
            name="napping",
        ),
        migrations.AddField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(null=True, verbose_name="Nap"),
        ),
        migrations.RunPython(
            set_sleep_nap_values, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(blank=True, verbose_name="Nap"),
        ),
    ]
